FROM jupyter
USER root
ENV DEBIAN_FRONTEND noninteractive
COPY perforce.pubkey /root/perforce.pubkey
RUN set -x\
  && apt-key add /root/perforce.pubkey\
  && echo "deb http://package.perforce.com/apt/ubuntu bionic release" > /etc/apt/sources.list.d/perforce.list\
  && apt-get -qq update\
  && apt-get -qq install --no-install-recommends\
  g++\
  gcc\
  helix-cli\
  libc6-i386\
  make\
  netbase\
  perl\
  python-dev\
  python\
  && apt-get -qq clean\
  && apt-get -qq autoremove\
  && rm -rf /var/lib/apt/lists/*\
  && rm -rf /root/.cache/ /root/perforce.pubkey

# netbase is required by dvsbuild.pl.
#
WORKDIR /
USER devel
RUN for P in setuptools ipykernel p4python==2017.2.1615960 crypto paramiko psutil; do python -m pip install --no-cache-dir --user -qq $P; done \
  && python -m ipykernel install --user
