version: "2.4"

services:
  notebook:
    image: eordian/notebook
    build:
      context: .
    env_file:
      - env.txt
    ports:
      - 8888:8888
    runtime: nvidia
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ~/.emacs.d/:/home/jovyan/.emacs.d/:ro
      - ../jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py:ro
      - /p4:/p4
      - /scratch:/scratch
      - /p4/julia-packages/:/opt/julia/
    working_dir: /
