version: "2.4"
services:
  db:
    image: eordian/postgres
    build:
      context: .
    environment:
      POSTGRES_PASSWORD: example
    runtime: nvidia
    restart: always
    # command: postgres -c 'shared_buffers=4GB' -c 'work_mem=1GB' -c 'maintenance_work_mem=1GB' -c 'max_worker_processes=32' -c 'max_parallel_workers=32' -c 'max_parallel_maintenance_workers=8' -c 'max_parallel_workers_per_gather=8'
    # user: root
    volumes:
      - /db/postgres:/var/lib/postgresql/data
      - /p4:/p4
      - /scratch:/scratch
    tmpfs:
      - /tmp
    stdin_open: true
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
