version: '3'

services:
  julia:
    image: eordian/julia
    build: .
    env_file:
      - env.txt
    stdin_open: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ./init.jl:/root/init.jl:ro
      - ~/code:/root/code
