version: '3'

services:
  julia:
    image: eordian/julia
    build: .
    command: bash
    env_file:
      - env.txt
    stdin_open: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ./init.jl:/root/init.jl
      # - ./startup.jl:/root/.julia/config/startup.jl
      # - ./pip.conf:/etc/pip.conf
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/pi/code:/root/code
    working_dir: /root
