version: "2.4"

services:
##########
  rapids:
    image: eordian/rapids_pymapd
    build:
      context: rapids
    # env_file:
    #   - env.txt
    ipc: host
    ports:
      - 8786-8888:8786-8888
    runtime: nvidia
    stdin_open: true
    tmpfs:
      - /tmp
    volumes:
      - /p4:/p4
      - /scratch:/scratch
    working_dir: /
##########
  omni:
    image: omnisci/core-os-cuda
    ipc: host
    runtime: nvidia
    restart: always
    volumes:
      - /p4/git/:/data/:ro ## the dir contains the data file.
      - omnisci-storage:/omnisci-storage
##########
volumes:
  omnisci-storage:
