version: "3.1"

services:
  jupyter:
    image: eordian/datascience-notebook
    build:
      context: .
    env_file:
      - env.txt
    ports:
      - 8888:8888
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /scratch:/scratch
      - /p4:/p4
      - /p4/julia-packages/:/opt/julia/
    working_dir: /
    env_file:
      - env.txt

##########
  # omni:
  #   image: omnisci/core-os-cpu
  #   # image: omnisci/core-os-cuda
  #   # runtime: nvidia
  #   restart: always
  #   volumes:
  #     - /p4/omnisci-storage:/omnisci-storage
  #     - /p4:/p4
  #     - /scratch:/scratch
  #   tmpfs:
  #     - /run
  #     - /tmp
    # ports:
    #   - 6273-6280:6273-6280
##########
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - /postgres:/var/lib/postgresql/data
      - /p4:/p4
      - /scratch:/scratch
    tmpfs:
      - /run
      - /tmp
    # ports:
    #   - 5432:5432

  adminer:
    image: adminer:master
    build:
      context: adminer
    restart: always
    ports:
      - 8080:8080
