version: "3" # ver 3 does not support nvidia runtime.

volumes:
  julia:

services:
  julia:
    image: eordian/julia
    build: .
    env_file:
      - env.txt
    stdin_open: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - julia:/root/.julia
      - ./init.jl:/root/init.jl
      - ./startup.jl:/root/.julia/config/startup.jl